# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc8982331ebd0cbaca4c980d83b611f72b6ed06ea028c587c92ec9f0b7b2a68e1622ee84115676015e751df644d13a6e060183da336fcee106024166ae3693db

test:
  secret_key_base: a3a222852e7c17f90514bd670ea894cf01fd80ea9b54039ffe6b7f6a99af9cc72c4f4727624cb5a34d3eb85eeb93830c637044894b25c9da681826d4585a5145

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
